[project]
name = "ml-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "pandas>=2.2.3",
    "pydantic>=2.11.5",
    "scikit-learn>=1.6.1",
    "uvicorn>=0.34.2",
]
